In [1]:
import pandas as pd
import numpy as np

Name: Satyadev Tummala <br>
Empid : 2000076426

In [31]:
df = pd.read_csv('cars.csv')

In [32]:
df.head(5)

,symboling,normalized losses,make,fuel-type,aspiration,num of doors,body style,drive wheels,engine location,wheel base,...,engine size,fuel system,bore,stroke,compression ratio,horsepower,peak rpm,city mpg,highway mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized losses  205 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num of doors       205 non-null    object
 6   body style         205 non-null    object
 7   drive wheels       205 non-null    object
 8   engine location    205 non-null    object
 9   wheel base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb weight        205 non-null    int64
 14  engine type        205 non-null    object
 15  num of cylinders   205 non-null    object
 16  engine size        205 non-null    int64
 17  fuel system        205 non-null    object
 18  bore               205 non-null    object
 19  stroke             205 non-null    object
 20  compression ratio  205 non-null    float64
 21  horsepower         205 non-null    object
 22  peak rpm           205 non-null    object
 23  city mpg           205 non-null    int64
 24  highway mpg        205 non-null    int64
 25  price              205 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

In [34]:
cols = df.columns

In [35]:
for col in cols:
    print(col,df[col].unique())

symboling [ 3  1  2  0 -1 -2]
normalized losses ['?' '164' '158' '192' '188' '121' '98' '81' '118' '148' '110' '145' '137'
 '101' '78' '106' '85' '107' '104' '113' '150' '129' '115' '93' '142'
 '161' '153' '125' '128' '122' '103' '168' '108' '194' '231' '119' '154'
 '74' '186' '83' '102' '89' '87' '77' '91' '134' '65' '197' '90' '94'
 '256' '95']
make ['alfa-romero' 'audi' 'bmw' 'chevrolet' 'dodge' 'honda' 'isuzu' 'jaguar'
 'mazda' 'mercedes-benz' 'mercury' 'mitsubishi' 'nissan' 'peugot'
 'plymouth' 'porsche' 'renault' 'saab' 'subaru' 'toyota' 'volkswagen'
 'volvo']
fuel-type ['gas' 'diesel']
aspiration ['std' 'turbo']
num of doors ['two' 'four' '?']
body style ['convertible' 'hatchback' 'sedan' 'wagon' 'hardtop']
drive wheels ['rwd' 'fwd' '4wd']
engine location ['front' 'rear']
wheel base [ 88.6  94.5  99.8  99.4 105.8  99.5 101.2 103.5 110.   88.4  93.7 103.3
  95.9  86.6  96.5  94.3  96.  113.  102.   93.1  95.3  98.8 104.9 106.7
 115.6  96.6 120.9 112.  102.7  93.   96.3  95.1  97.2 100.4  91.3  99.2
 107.9 114.2 108.   89.5  98.4  96.1  99.1  93.3  97.   96.9  95.7 102.4
 102.9 104.5  97.3 104.3 109.1]
length [168.8 171.2 176.6 177.3 192.7 178.2 176.8 189.  193.8 197.  141.1 155.9
 158.8 157.3 174.6 173.2 144.6 150.  163.4 157.1 167.5 175.4 169.1 170.7
 172.6 199.6 191.7 159.1 166.8 169.  177.8 175.  190.9 187.5 202.6 180.3
 208.1 199.2 178.4 173.  172.4 165.3 170.2 165.6 162.4 173.4 181.7 184.6
 178.5 186.7 198.9 167.3 168.9 175.7 181.5 186.6 156.9 157.9 172.  173.5
 173.6 158.7 169.7 166.3 168.7 176.2 175.6 183.5 187.8 171.7 159.3 165.7
 180.2 183.1 188.8]
width [64.1 65.5 66.2 66.4 66.3 71.4 67.9 64.8 66.9 70.9 60.3 63.6 63.8 64.6
 63.9 64.  65.2 62.5 66.  61.8 69.6 70.6 64.2 65.7 66.5 66.1 70.3 71.7
 70.5 72.  68.  64.4 65.4 68.4 68.3 65.  72.3 66.6 63.4 65.6 67.7 67.2
 68.9 68.8]
height [48.8 52.4 54.3 53.1 55.7 55.9 52.  53.7 56.3 53.2 50.8 50.6 59.8 50.2
 52.6 54.5 58.3 53.3 54.1 51.  53.5 51.4 52.8 47.8 49.6 55.5 54.4 56.5
 58.7 54.9 56.7 55.4 54.8 49.4 51.6 54.7 55.1 56.1 49.7 56.  50.5 55.2
 52.5 53.  59.1 53.9 55.6 56.2 57.5]
curb weight [2548 2823 2337 2824 2507 2844 2954 3086 3053 2395 2710 2765 3055 3230
 3380 3505 1488 1874 1909 1876 2128 1967 1989 2191 2535 2811 1713 1819
 1837 1940 1956 2010 2024 2236 2289 2304 2372 2465 2293 2734 4066 3950
 1890 1900 1905 1945 1950 2380 2385 2500 2410 2443 2425 2670 2700 3515
 3750 3495 3770 3740 3685 3900 3715 2910 1918 1944 2004 2145 2370 2328
 2833 2921 2926 2365 2405 2403 1889 2017 1938 1951 2028 1971 2037 2008
 2324 2302 3095 3296 3060 3071 3139 3020 3197 3430 3075 3252 3285 3485
 3130 2818 2778 2756 2800 3366 2579 2460 2658 2695 2707 2758 2808 2847
 2050 2120 2240 2190 2340 2510 2290 2455 2420 2650 1985 2040 2015 2280
 3110 2081 2109 2275 2094 2122 2140 2169 2204 2265 2300 2540 2536 2551
 2679 2714 2975 2326 2480 2414 2458 2976 3016 3131 3151 2261 2209 2264
 2212 2319 2254 2221 2661 2563 2912 3034 2935 3042 3045 3157 2952 3049
 3012 3217 3062]
engine type ['dohc' 'ohcv' 'ohc' 'l' 'rotor' 'ohcf' 'dohcv']
num of cylinders ['four' 'six' 'five' 'three' 'twelve' 'two' 'eight']
engine size [130 152 109 136 131 108 164 209  61  90  98 122 156  92  79 110 111 119
 258 326  91  70  80 140 134 183 234 308 304  97 103 120 181 151 194 203
 132 121 146 171 161 141 173 145]
fuel system ['mpfi' '2bbl' 'mfi' '1bbl' 'spfi' '4bbl' 'idi' 'spdi']
bore ['3.47' '2.68' '3.19' '3.13' '3.50' '3.31' '3.62' '2.91' '3.03' '2.97'
 '3.34' '3.60' '2.92' '3.15' '3.43' '3.63' '3.54' '3.08' '?' '3.39' '3.76'
 '3.58' '3.46' '3.80' '3.78' '3.17' '3.35' '3.59' '2.99' '3.33' '3.70'
 '3.61' '3.94' '3.74' '2.54' '3.05' '3.27' '3.24' '3.01']
stroke ['2.68' '3.47' '3.40' '2.80' '3.19' '3.39' '3.03' '3.11' '3.23' '3.46'
 '3.90' '3.41' '3.07' '3.58' '4.17' '2.76' '3.15' '?' '3.16' '3.64' '3.10'
 '3.35' '3.12' '3.86' '3.29' '3.27' '3.52' '2.19' '3.21' '2.90' '2.07'
 '2.36' '2.64' '3.08' '3.50' '3.54' '2.87']
compression ratio [ 9.   10.    8.    8.5   8.3   7.    8.8   9.5   9.6   9.41  9.4   7.6
  9.2  10.1   9.1   8.1  11.5   8.6  22.7  22.   21.5   7.5  21.9   7.8
  8.4  21.    8.7   9.31  9.3   7.7  22.5  23.  ]
horsepower ['111' '154' '102' '115' '110' '140' '160' '101' '121' '182' '48' '70'
 '68' '88' '145' '58' '76' '60' '86' '100' '78' '90' '176' '262' '135'
 '84' '64' '120' '72' '123' '155' '184' '175' '116' '69' '55' '97' '152'
 '200' '95' '142' '143' '207' '288' '?' '73' '82' '94' '62' '56' '112'
 '92' '161' '156' '52' '85' '114' '162' '134' '106']
peak rpm ['5000' '5500' '5800' '4250' '5400' '5100' '4800' '6000' '4750' '4650'
 '4200' '4350' '4500' '5200' '4150' '5600' '5900' '5750' '?' '5250' '4900'
 '4400' '6600' '5300']
city mpg [21 19 24 18 17 16 23 20 15 47 38 37 31 49 30 27 25 13 26 36 22 14 45 28
 32 35 34 29 33]
highway mpg [27 26 30 22 25 20 29 28 53 43 41 38 24 54 42 34 33 31 19 17 23 32 39 18
 16 37 50 36 47 46]
price ['13495' '16500' '13950' '17450' '15250' '17710' '18920' '23875' '?'
 '16430' '16925' '20970' '21105' '24565' '30760' '41315' '36880' '5151'
 '6295' '6575' '5572' '6377' '7957' '6229' '6692' '7609' '8558' '8921'
 '12964' '6479' '6855' '5399' '6529' '7129' '7295' '7895' '9095' '8845'
 '10295' '12945' '10345' '6785' '11048' '32250' '35550' '36000' '5195'
 '6095' '6795' '6695' '7395' '10945' '11845' '13645' '15645' '8495'
 '10595' '10245' '10795' '11245' '18280' '18344' '25552' '28248' '28176'
 '31600' '34184' '35056' '40960' '45400' '16503' '5389' '6189' '6669'
 '7689' '9959' '8499' '12629' '14869' '14489' '6989' '8189' '9279' '5499'
 '7099' '6649' '6849' '7349' '7299' '7799' '7499' '7999' '8249' '8949'
 '9549' '13499' '14399' '17199' '19699' '18399' '11900' '13200' '12440'
 '13860' '15580' '16900' '16695' '17075' '16630' '17950' '18150' '12764'
 '22018' '32528' '34028' '37028' '9295' '9895' '11850' '12170' '15040'
 '15510' '18620' '5118' '7053' '7603' '7126' '7775' '9960' '9233' '11259'
 '7463' '10198' '8013' '11694' '5348' '6338' '6488' '6918' '7898' '8778'
 '6938' '7198' '7788' '7738' '8358' '9258' '8058' '8238' '9298' '9538'
 '8449' '9639' '9989' '11199' '11549' '17669' '8948' '10698' '9988'
 '10898' '11248' '16558' '15998' '15690' '15750' '7975' '7995' '8195'
 '9495' '9995' '11595' '9980' '13295' '13845' '12290' '12940' '13415'
 '15985' '16515' '18420' '18950' '16845' '19045' '21485' '22470' '22625']

In [90]:
for col in cols:
    if df[col].isna().any():
        print(col)

bore
stroke
horsepower

,symboling,normalized losses,make,fuel-type,aspiration,num of doors,body style,drive wheels,engine location,wheel base,...,engine size,fuel system,bore,stroke,compression ratio,horsepower,peak rpm,city mpg,highway mpg,price
55,3,150,mazda,gas,std,two,hatchback,rwd,front,95.3,...,70,4bbl,NaN,NaN,9.4,101,6000,17,23,10945
56,3,150,mazda,gas,std,two,hatchback,rwd,front,95.3,...,70,4bbl,NaN,NaN,9.4,101,6000,17,23,11845
57,3,150,mazda,gas,std,two,hatchback,rwd,front,95.3,...,70,4bbl,NaN,NaN,9.4,101,6000,17,23,13645
58,3,150,mazda,gas,std,two,hatchback,rwd,front,95.3,...,80,mpfi,NaN,NaN,9.4,135,6000,16,23,15645

In [25]:
# columns containing '?' : normalized losses,num of doors,peak rpm,price

# now replacing those values

In [36]:
df.replace({"?":np.nan},inplace=True)

In [127]:
for col in df.columns:
    df[col].fillna(df[col].mode().iloc[0],inplace=True)

In [128]:
# Check for missing values
for col in cols:
    if df[col].isna().any():
        print(col)

In [51]:
# clean dataset

In [52]:
df

,symboling,normalized losses,make,fuel-type,aspiration,num of doors,body style,drive wheels,engine location,wheel base,...,engine size,fuel system,bore,stroke,compression ratio,horsepower,peak rpm,city mpg,highway mpg,price
0,3,161,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,161,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,161,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

# questions
1)What percentage of cars will be suitable for a family (i.e. num of doors=4, price <20,000 & mileage >17)? <br>
2)Which company has generated more car options for customers?<br>
3)What is the ratio of diesel cars to that gas ones?<br>
4)What is the count of performance cars present in the dataset (horsepower > 150)?<br>
5)Which is the most compact among all cars?<br>
6)What are the main factors that are associated with the mileage of a car?<br>
7)What percentage of cars are budget-friendly (price < 10,00)?<br>
8)Which cars are the most efficient of all (city mpg >= 30)?<br>
9)What percentage of data is missing from the dataset?<br>
10)Which feature of the car affects the most to the pricing?<br>

In [53]:
#q1

In [60]:
df['price'] = df['price'].astype('int64')

In [68]:
numFamilyCars = df[(df['num of doors'] == 'four') & (df['price'] < 20000) & (df['city mpg'] > 17)].count().iloc[0]

In [137]:
totalCars = df.count().iloc[0]
percentage = numFamilyCars / totalCars
print('total cars',totalCars)

total cars 205

In [71]:
percentage * 100

47.3170731707317

In [72]:
#q2

In [83]:
df.groupby('make')['make'].count().sort_values(ascending=False).idxmax()

'toyota'

In [84]:
#q3

In [85]:
df['fuel-type'].unique()

array(['gas', 'diesel'], dtype=object)

In [107]:
countGas  = int(df[df['fuel-type'] == 'gas'].count().iloc[0])
countDisel = int(df[df['fuel-type'] == 'diesel'].count().iloc[0])
print("number of gas cars:",countGas)
print("number of disel cars:",countDisel)
totalCars = df.count().iloc[0]
ratio = countDisel/countGas

print("the ratio of disel w.r.t to gas:",str(ratio))

number of gas cars: 185
number of disel cars: 20
the ratio of disel w.r.t to gas: 0.10810810810810811

In [106]:
# q4

In [114]:
df['horsepower'].fillna(df['horsepower'].mode().iloc[0],inplace=True)

In [115]:
df['horsepower']  = df['horsepower'].astype('int64')

In [118]:
df[df['horsepower'] > 150].count().iloc[0]

32

In [119]:
# q5

In [134]:
df[df['body style'] == 'hatchback'].sort_values('curb weight').iloc[0]

symboling                    2
normalized losses          121
make                 chevrolet
fuel-type                  gas
aspiration                 std
num of doors               two
body style           hatchback
drive wheels               fwd
engine location          front
wheel base                88.4
length                   141.1
width                     60.3
height                    53.2
curb weight               1488
engine type                  l
num of cylinders         three
engine size                 61
fuel system               2bbl
bore                      2.91
stroke                    3.03
compression ratio          9.5
horsepower                  48
peak rpm                  5100
city mpg                    47
highway mpg                 53
price                     5151
Name: 18, dtype: object

In [135]:
#q6

In [158]:
df.corr()[['city mpg','highway mpg']]

                   city mpg  highway mpg
symboling         -0.035823     0.034606
wheel base        -0.470414    -0.544082
length            -0.670909    -0.704662
width             -0.642704    -0.677218
height            -0.048640    -0.107358
curb weight       -0.757414    -0.797465
engine size       -0.653658    -0.677470
compression ratio  0.324701     0.265201
horsepower        -0.796862    -0.768096
city mpg           1.000000     0.971337
highway mpg        0.971337     1.000000
price             -0.667215    -0.690173

<B>from the above table we can figure out the main factors that affect the mileage of the car are:
length, width, curb weight, engine size, horsepower, highway mpg, price
the corr is either positive or negative for these features and above 0.5</B>

In [161]:
#q7

In [142]:
bugetCars = df[df['price'] < 10000].count().iloc[0]
percentageCars = (bugetCars / totalCars) * 100
print("Percentage of cars that are budger friendly",percentageCars)

Percentage of cars that are budger friendly 47.80487804878049

In [143]:
#q8

In [170]:
df[df['city mpg'] >= 30].sort_values(by='city mpg',ascending = False)

,symboling,normalized losses,make,fuel-type,aspiration,num of doors,body style,drive wheels,engine location,wheel base,...,engine size,fuel system,bore,stroke,compression ratio,horsepower,peak rpm,city mpg,highway mpg,price
30,2,137,honda,gas,std,two,hatchback,fwd,front,86.6,...,92,1bbl,2.91,3.41,9.60,58,4800,49,54,6479
18,2,121,chevrolet,gas,std,two,hatchback,fwd,front,88.4,...,61,2bbl,2.91,3.03,9.50,48,5100,47,53,5151
90,1,128,nissan,diesel,std,two,sedan,fwd,front,94.5,...,103,idi,2.99,3.47,21.90,55,4800,45,50,7099
20,0,81,chevrolet,gas,std,four,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.60,70,5400,38,43,6575
160,0,91,toyota,gas,std,four,sedan,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.00,70,4800,38,47,7738
32,1,101,honda,gas,std,two,hatchback,fwd,front,93.7,...,79,1bbl,2.91,3.07,10.10,60,5500,38,42,5399
159,0,91,toyota,diesel,std,four,hatchback,fwd,front,95.7,...,110,idi,3.27,3.35,22.50,56,4500,38,47,7788
44,1,161,isuzu,gas,std,two,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.60,70,5400,38,43,13499
45,0,161,isuzu,gas,std,four,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.60,70,5400,38,43,13499
19,1,98,chevrolet,gas,std,two,hatchback,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.60,70,5400,38,43,6295
21,1,118,dodge,gas,std,two,hatchback,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.41,68,5500,37,41,5572
187,2,94,volkswagen,diesel,turbo,four,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.00,68,4500,37,42,9495
184,2,94,volkswagen,diesel,std,four,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.00,52,4800,37,46,7995
182,2,122,volkswagen,diesel,std,two,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.00,52,4800,37,46,7775
118,1,119,plymouth,gas,std,two,hatchback,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68,5500,37,41,5572
76,2,161,mitsubishi,gas,std,two,hatchback,fwd,front,93.7,...,92,2bbl,2.97,3.23,9.40,68,5500,37,41,5389
63,0,161,mazda,diesel,std,four,sedan,fwd,front,98.8,...,122,idi,3.39,3.39,22.70,64,4650,36,42,10795
150,1,87,toyota,gas,std,two,hatchback,fwd,front,95.7,...,92,2bbl,3.05,3.03,9.00,62,4800,35,39,5348
158,0,91,toyota,diesel,std,four,sedan,fwd,front,95.7,...,110,idi,3.27,3.35,22.50,56,4500,34,36,7898
192,0,161,volkswagen,diesel,turbo,four,sedan,fwd,front,100.4,...,97,idi,3.01,3.40,23.00,68,4500,33,38,13845
141,0,102,subaru,gas,std,four,sedan,fwd,front,97.2,...,108,2bbl,3.62,2.64,9.50,82,4800,32,37,7126
53,1,113,mazda,gas,std,four,sedan,fwd,front,93.1,...,91,2bbl,3.03,3.15,9.00,68,5000,31,38,6695
97,1,103,nissan,gas,std,four,wagon,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.40,69,5200,31,37,7999
24,1,148,dodge,gas,std,four,hatchback,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68,5500,31,38,6229
25,1,148,dodge,gas,std,four,sedan,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68,5500,31,38,6692
26,1,148,dodge,gas,std,four,sedan,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68,5500,31,38,7609
31,2,137,honda,gas,std,two,hatchback,fwd,front,86.6,...,92,1bbl,2.91,3.41,9.20,76,6000,31,38,6855
153,0,77,toyota,gas,std,four,wagon,fwd,front,95.7,...,92,2bbl,3.05,3.03,9.00,62,4800,31,37,6918
152,1,74,toyota,gas,std,four,hatchback,fwd,front,95.7,...,92,2bbl,3.05,3.03,9.00,62,4800,31,38,6488
151,1,87,toyota,gas,std,two,hatchback,fwd,front,95.7,...,92,2bbl,3.05,3.03,9.00,62,4800,31,38,6338
138,2,83,subaru,gas,std,two,hatchback,fwd,front,93.7,...,97,2bbl,3.62,2.36,9.00,69,4900,31,36,5118
122,1,154,plymouth,gas,std,four,sedan,fwd,front,93.7,...,98,2bbl,2.97,3.23,9.40,68,5500,31,38,7609
121,1,154,plymouth,gas,std,four,sedan,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68,5500,31,38,6692
54,1,113,mazda,gas,std,four,sedan,fwd,front,93.1,...,91,2bbl,3.08,3.15,9.00,68,5000,31,38,7395
98,2,168,nissan,gas,std,two,hardtop,fwd,front,95.1,...,97,2bbl,3.15,3.29,9.40,69,5200,31,37,8249
120,1,154,plymouth,gas,std,four,hatchback,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68,5500,31,38,6229
96,1,122,nissan,gas,std,four,sedan,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.40,69,5200,31,37,7499
89,1,128,nissan,gas,std,two,sedan,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.40,69,5200,31,37,5499
52,1,104,mazda,gas,std,two,hatchback,fwd,front,93.1,...,91,2bbl,3.03,3.15,9.00,68,5000,31,38,6795
66,0,161,mazda,diesel,std,four,sedan,rwd,front,104.9,...,134,idi,3.43,3.64,22.00,72,4200,31,39,18344
51,1,104,mazda,gas,std,two,hatchback,fwd,front,93.1,...,91,2bbl,3.03,3.15,9.00,68,5000,31,38,6095
77,2,161,mitsubishi,gas,std,two,hatchback,fwd,front,93.7,...,92,2bbl,2.97,3.23,9.40,68,5500,31,38,6189
78,2,161,mitsubishi,gas,std,two,hatchback,fwd,front,93.7,...,92,2bbl,2.97,3.23,9.40,68,5500,31,38,6669
91,1,128,nissan,gas,std,two,sedan,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.40,69,5200,31,37,6649
22,1,118,dodge,gas,std,two,hatchback,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68,5500,31,38,6377
93,1,103,nissan,gas,std,four,wagon,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.40,69,5200,31,37,7349
94,1,128,nissan,gas,std,two,sedan,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.40,69,5200,31,37,7299
95,1,128,nissan,gas,std,two,hatchback,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.40,69,5200,31,37,7799
92,1,122,nissan,gas,std,four,sedan,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.40,69,5200,31,37,6849
35,0,110,honda,gas,std,four,sedan,fwd,front,96.5,...,92,1bbl,2.91,3.41,9.20,76,6000,30,34,7295
50,1,104,mazda,gas,std,two,hatchback,fwd,front,93.1,...,91,2bbl,3.03,3.15,9.00,68,5000,30,31,5195
36,0,78,honda,gas,std,four,wagon,fwd,front,96.5,...,92,1bbl,2.92,3.41,9.20,76,6000,30,34,7295
156,0,91,toyota,gas,std,four,sedan,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.00,70,4800,30,37,6938
157,0,91,toyota,gas,std,four,hatchback,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.00,70,4800,30,37,7198
34,1,101,honda,gas,std,two,hatchback,fwd,front,93.7,...,92,1bbl,2.91,3.41,9.20,76,6000,30,34,7129
33,1,101,honda,gas,std,two,hatchback,fwd,front,93.7,...,92,1bbl,2.91,3.41,9.20,76,6000,30,34,6529
174,-1,65,toyota,diesel,turbo,four,sedan,fwd,front,102.4,...,110,idi,3.27,3.35,22.50,73,4500,30,33,10698

In [145]:
#q9

In [148]:
df[df.isna()].count()
# zero missing records so percentage of missing data is 0, since we filled '?' previously the data now is cleaned

symboling            0
normalized losses    0
make                 0
fuel-type            0
aspiration           0
num of doors         0
body style           0
drive wheels         0
engine location      0
wheel base           0
length               0
width                0
height               0
curb weight          0
engine type          0
num of cylinders     0
engine size          0
fuel system          0
bore                 0
stroke               0
compression ratio    0
horsepower           0
peak rpm             0
city mpg             0
highway mpg          0
price                0
dtype: int64

In [149]:
# q10

In [166]:
df.corr()['price']

symboling           -0.082396
wheel base           0.582915
length               0.682528
width                0.729009
height               0.133761
curb weight          0.820807
engine size          0.861769
compression ratio    0.070789
horsepower           0.759731
city mpg            -0.667215
highway mpg         -0.690173
price                1.000000
Name: price, dtype: float64

<b>The feature that affects the car price most is the enginge_size since it has the highest correleation </b>